[package]
name = "l-system"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
euler = "0.4.1"
rand = "0.8.5"
rand_chacha = "0.3.1"
raylib = "3.7.0"
